name: Build

on:
  pull_request:
    branches:
      - develop
      - master
      - testing
  push:
    branches:
      - develop
      - testing
  workflow_call:
  workflow_dispatch:

env:
  NODE_VERSION: 22

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Node packages
        run: npm ci
      - name: Linting check
        run: npm run lint
      - name: Build
        run: npm run build
