name: Build

on:
  pull_request:
    branches:
      - develop
      - master
      - testing
  push:
    branches:
      - develop
      - testing
  workflow_call:
  workflow_dispatch:

env:
  NODE_VERSION: 22

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Node packages
        run: npm install
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Linting check
        run: npm run lint
      - name: Build
        run: npm run build
